### ISSUE TITLE
Engine drops object locking when GC physically removes lock-object

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-node#1227]
## Expected Behavior
When lock-object is removed (inhumed in terms of storage engine), all corresponding regular objects should be unlocked.

## Current Behavior
1. Regular objects are unlocked only when lock-object is removed by GC.
2. GC unlocks regular objects stored in the same shard as lock-object.

## Context
In https://github.com/nspcc-dev/neofs-node/pull/1181 metabase drops object locking during `freePotentialLocks()`. This function invoked during `Inhume` of non-regular object with `GCMark`. 

To solve (1) we can invoke `freePontantialLocks()` during any `Inhume(tombstone)` invocation. However this won't affect objects which are locked in other shards. 

(2) is similar to the issue of objects with expired tombstone that we address in https://github.com/nspcc-dev/neofs-node/issues/378. When tombstone is expired, engine has to remove all corresponding objects in all shards. To solve that, shard invokes `expiredTombstonesCallback()` to go through all shards.

However expired tombstone issue can be solved differently, see proposed solution in https://github.com/nspcc-dev/neofs-node/issues/1226 We want a robust solution for locks as well, one more callback does not look appealing.

**Comment by alexvanin** [comment]
Maybe engine should preemptively discover lock-object removal and initiate object unlocking in all shards? To do that we have to implement `Unlock()` method on shard \ metabase.

**Comment by alexvanin** [comment]
Expected behavior according to the latest discussions:
1. Regular objects are unlocked as soon as lock objects are expired
2. Lock objects must always expire, otherwise they are not valid
3. Lock objects cannot be deleted, only expired

This makes lock object behavior consistent (no removable locks). Specification may omit such details, so it should be fixed.
Locks expiration should trigger lock index update in metabase, so regular object can be removed from now on.

As for temporary locks, we should use different scheme, e.g. alphabet-signed lock notification, that will be parsed by all storage nodes.

**Comment by alexvanin** [comment]
Control service should keep an ability to set GCMark on LOCK object anyway (by @realloc )

**Comment by cthulhu-rider** [comment]
Then there will be 3 types of `Inhume`:

1. with tombstone
2. regular GC mark
3. force GC mark

**Comment by carpawell** [comment]
From issue body:

> When lock-object is removed (inhumed in terms of storage engine), all corresponding regular objects should be unlocked.

it was true for expired LOCKs and still true.

> 2. GC unlocks regular objects stored in the same shard as lock-object.

I added [PoC](https://github.com/nspcc-dev/neofs-node/pull/1440) that solves it.

However, it is still not clear what behavior is expected when working with LOCK objects.
#1440 fixes current behavior (according to the current implementation of the LOCK objects) but does not restrict LOCK object deletion. As I see, LOCK object deletion is still a valid operation, locking objects without expiration also is valid. And that was valid from the beginning of LOCK's existence. Also, I do not see any statements about LOCK expiration in the [API](https://github.com/nspcc-dev/neofs-api/blob/8bf98ec983cb324fef4f56fc0088246ba918078c/lock/types.proto#L10) (for regular objects the same [means](https://github.com/nspcc-dev/neofs-api/blob/8bf98ec983cb324fef4f56fc0088246ba918078c/object/types.proto#L123) that object could exist without expiration attr (infinite life), at least current implementation allows that).

If https://github.com/nspcc-dev/neofs-node/issues/1227#issuecomment-1083186577 is still true I suggest fixing that in the API repo first. And then open another PR that corrects implementation (and close #1440 as incorrect). If not: clarify LOCK flow and fix it according to the updated info.

> Control service should keep an ability to set GCMark on LOCK object anyway (by @realloc )

That also required clarifying: should the node unlock all the objects after LOCK object removal or it is just an ability to remove any object by the node owner?

/cc @realloc, @cthulhu-rider, @alexvanin, @fyrchik

**Comment by alexvanin** [comment]
> If https://github.com/nspcc-dev/neofs-node/issues/1227#issuecomment-1083186577 is still true I suggest fixing that in the API repo first. And then open another PR that corrects implementation (and close https://github.com/nspcc-dev/neofs-node/pull/1440 as incorrect). If not: clarify LOCK flow and fix it according to the updated info.

I think it is our latest decision, therefore we should change API first, agree. 

> That also requires clarifying: should the node unlock all the objects after LOCK object removal or it is just an ability to remove any object by the node owner?

When LOCK object receives GCMark from control service, the object is inhumed, right? If so, then `When lock-object is removed (inhumed in terms of storage engine), all corresponding regular objects should be unlocked` comes into place. Locked objects should be unlocked after that. If it is working already, then great!

**Comment by carpawell** [comment]
> I think it is our latest decision, therefore we should change API first, agree.

Ok, I will open the corresponding PR.

> If it is working already, then great!

No, it does not work yet, require #1440 but changed:
1. Restrict Inhuming by not the control service (smth like https://github.com/nspcc-dev/neofs-node/issues/1227#issuecomment-1089904759 I guess);
2. Restrict LOCKing without expiration epoch;
3. Same changes in CLI.

Does that correspond with the expectation about LOCK object UX?

**Comment by alexvanin** [comment]
> Does that correspond with the expectation about LOCK object UX?

It sounds right at this point. Can we use feature workflow as we did with homomorphic hash disabling so we can test it in all levels, including gateway, before the merge?

**Comment by carpawell** [comment]
> Can we use feature workflow

Sure.

**Comment by KirillovDenis** [comment]
Currently, objects can be removed right after lock is expired on [this branch](https://github.com/nspcc-dev/neofs-node/tree/fix/correct-lock-objects). (Checked with s3)
